import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        padding: 20,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 8,
        marginTop: -13,
    },
    backBtn: {
        position: 'absolute',
        left: -10,
        padding: 8,
        zIndex: 2,
    },
    backIcon: {
        width: 24,
        height: 24,
        resizeMode: 'contain',
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#222',
    },
    divider: {
        height: 1,
        backgroundColor: '#BDBDBD',

        marginBottom: 18,
    },
    imageUploadBtn: {
        backgroundColor: '#D9D9D9',
        borderRadius: 12,
        height: 60,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 18,
        marginTop: 20,
    },
    cameraIcon: {
        width: 22,
        height: 22,
        marginRight: 8,
        resizeMode: 'contain',
    },
    imageUploadText: {
        color: '#222',
        fontSize: 16,
        fontWeight: 'bold',
    },
    input: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#BDBDBD',
        borderRadius: 8,
        height: 44,
        paddingHorizontal: 14,
        fontSize: 15,
        color: '#222',
        marginBottom: 8,
    },
    inputHint: {
        color: '#BDBDBD',
        fontSize: 13,
        marginBottom: 8,
        marginLeft: 4,
    },
    dropdownWrap: {
        position: 'relative',
        marginBottom: 8,
    },
    dropdown: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#BDBDBD',
        borderRadius: 8,
        height: 44,
        paddingHorizontal: 14,
        fontSize: 15,
        color: '#222',
        justifyContent: 'center',
        flexDirection: 'row',
        alignItems: 'center',
    },
    dropdownIcon: {
        position: 'absolute',
        right: 14,
        top: 12,
        width: 20,
        height: 20,
    },
    dropdownText: {
        flex: 1,
        fontSize: 15,
    },
    priceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#BDBDBD',
        borderRadius: 8,
        height: 44,
        marginBottom: 8,
    },
    pricePrefix: {
        color: '#BDBDBD',
        fontSize: 16,
        marginLeft: 12,
        marginRight: 4,
    },
    priceInput: {
        flex: 1,
        fontSize: 15,
        color: '#222',
        paddingVertical: 0,
        paddingHorizontal: 0,
    },
    priceSuffix: {
        color: '#BDBDBD',
        fontSize: 16,
        marginRight: 12,
        marginLeft: 4,
    },
    textarea: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#BDBDBD',
        borderRadius: 8,
        minHeight: 150,
        paddingHorizontal: 14,
        paddingVertical: 10,
        fontSize: 15,
        color: '#222',
        marginBottom: 16,
        textAlignVertical: 'top',
    },
    submitBtn: {
        backgroundColor: '#22CC6B',
        padding: 15,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 30,
    },
    submitBtnDisabled: {
        backgroundColor: '#D9D9D9',
        opacity: 0.7,
    },
    submitBtnText: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
    },
    categoryList: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#BDBDBD',
        borderRadius: 8,
        marginTop: 2,
        marginBottom: 8,
        paddingVertical: 4,
        zIndex: 10,
    },
    categoryItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 14,
    },
    categoryIcon: {
        width: 28,
        height: 28,
        marginRight: 10,
    },
    categoryLabel: {
        fontSize: 16,
        color: '#222',
    },
    overlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        zIndex: 1000,
        elevation: 5,
    },

    categoryModal: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'white',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        padding: 20,
        zIndex: 1001,
        maxHeight: '80%',
        elevation: 6,
    },

    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingBottom: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E5E5',
    },

    modalTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#222',
    },

    modalClose: {
        fontSize: 20,
        color: '#222',
        padding: 5,
    },

    categoryList: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        paddingHorizontal: 10,
    },

    categoryItem: {
        width: '48%',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F8F8',
        padding: 15,
        borderRadius: 10,
        marginBottom: 15,
    },

    categoryIcon: {
        width: 24,
        height: 24,
        marginRight: 10,
    },

    categoryLabel: {
        fontSize: 14,
        color: '#222',
        flex: 1,
        fontWeight: 'bold',
    },

    dim: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.5)',
        zIndex: 1000,
    },
});

export default styles;
