import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        position: 'absolute',
        top: 50,
        left: 0,
        right: 0,
        bottom: 0,
    },
    header: {
        alignItems: 'center',
        padding: 15,
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        textAlign: 'center',
        fontFamily: 'System',
    },
    content: {
        flex: 1,
        paddingHorizontal: 16,
        paddingTop: -40,
    },
    section: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        marginTop: -10,
    },
    menuItem: {
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 0,
        marginRight: 0,
        shadowColor: undefined,
        shadowOffset: undefined,
        shadowOpacity: undefined,
        shadowRadius: undefined,
        elevation: undefined,
        minWidth: undefined,
        minHeight: undefined,
        alignSelf: 'center',
        backgroundColor: undefined,
        borderRadius: undefined,
        paddingVertical: 0,
        paddingHorizontal: 0,
    },
    menuContent: {
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    menuContent2: {
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 20,
    },
    menuIcon: {
        fontSize: 36,
        marginRight: 0,
        marginBottom: 6,
        textAlign: 'center',
    },
    menuText: {
        fontSize: 16,
        fontWeight: '500',
        color: '#222',
        textAlign: 'center',
        fontWeight: 'bold',
    },
    loadingText: {
        marginLeft: 10,
        fontSize: 12,
        color: '#999',
        fontWeight: 'bold',
    },
    writeButton: {
        position: 'absolute',
        right: 20,
        bottom: 80,
        backgroundColor: '#22CC6B',
        paddingHorizontal: 25,
        paddingVertical: 15,
        borderRadius: 30,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        marginBottom: 40,
        flexDirection: 'row',
        alignItems: 'center',
    },
    writeButtonText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 22,
    },
    writeIcon: {
        width: 17,
        height: 17,
        marginLeft: 3,
    },
    divider: {
        height: 1,
        backgroundColor: '#eee',
        marginHorizontal: 0,
        marginTop: 10,
        width: '100%',
    },
}); 