import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 18,
        marginTop: -20,
        padding: 24,
    },
    backIcon: {
        width: 28,
        height: 28,
        marginRight: 8,
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        flex: 1,
        textAlign: 'center',
        marginRight: 36,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginTop: -20,
        marginBottom: 8,
        color: '#222',
        padding: 24,
    },
    result: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#22CC6B',
        marginBottom: 8,
        marginTop: -45,
        padding: 24,
    },
    inputSummaryRow: {
        flexDirection: 'row',
        marginBottom: 8,
        padding: 24,
        marginTop: -40,
    },
    inputSummaryBox: {
        borderRadius: 8,
        paddingVertical: 4,
        paddingHorizontal: 14,
        marginRight: 8,
        backgroundColor: '#D9D9D9',
    },
    inputSummaryText: {
        fontSize: 15,
        color: '#222',
        fontWeight: 'bold',
    },
    resultDesc: {
        fontSize: 13,
        color: '#888',
        marginBottom: 18,
        padding: 24,
        marginTop: -40,
    },
    tableTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginTop: -10,
        marginBottom: 8,
        color: '#222',
        padding: 24,
    },
    tableTitle2: {
        fontSize: 13,
        marginTop: -10,
        marginBottom: 8,
        color: 'black',
        padding: 24,
        marginLeft: 100,
    },
    tableWrap: {
        borderWidth: 1,
        borderColor: '#D9D9D9',
        borderRadius: 10,
        overflow: 'hidden',
        marginBottom: 18,
    },
    tableHeaderRow: {
        flexDirection: 'row',
        backgroundColor: '#F6FFF9',
        borderBottomWidth: 1,
        borderColor: '#D9D9D9',
    },
    tableHeader: {
        flex: 1,
        fontSize: 14,
        fontWeight: 'bold',
        color: '#222',
        textAlign: 'center',
        paddingVertical: 10,
    },
    tableHeaderGreen: {
        color: '#22CC6B',
    },
    tableRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderColor: '#F0F0F0',
        backgroundColor: '#fff',
    },
    tableCell: {
        flex: 1,
        fontSize: 14,
        color: '#222',
        textAlign: 'center',
        paddingVertical: 10,
    },
    tableCellGreen: {
        color: '#22CC6B',
        fontWeight: 'bold',
    },
    tableUnitRow: {
        backgroundColor: '#F6FFF9',
        borderTopWidth: 1,
        borderColor: '#D9D9D9',
    },
    tableUnitText: {
        fontSize: 12,
        color: '#888',
        textAlign: 'right',
        paddingVertical: 6,
        paddingRight: 12,
    },
    infoBox: {
        backgroundColor: '#F8F8F8',
        borderRadius: 10,
        padding: 16,
        marginBottom: 16,
    },
    infoTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#222',
        marginTop: 8,
        marginBottom: 4,
    },
    infoText: {
        fontSize: 13,
        color: '#444',
        marginBottom: 2,
    },
    sourceText: {
        fontSize: 12,
        color: '#888',
        textAlign: 'right',
        marginTop: 8,
        marginBottom: 12,
    },
    tableImage: {
        width: 394,
        height: 592,
        marginTop: -30,
        marginRight: 35,
        resizeMode: 'contain',
    },
    line: {
        borderBottomWidth: 3,
        borderColor: '#8C8A8A',
        marginTop: -10,
        marginBottom: 10,
    },
});
