import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 16,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
  },
  backBtn: {
    padding: 4,
    marginRight: 8,
  },
  backIcon: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: 'bold',
    color: '#222',
    marginRight: 4, // 완료 버튼 공간 확보
  },
  doneBtn: {
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  doneBtnText: {
    color: '#22CC6B',
    fontWeight: 'bold',
    fontSize: 17,
  },
  profileImgSection: {
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 18,
  },
  profileImgWrapper: {
    width: 92,
    height: 92,
    borderRadius: 46,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  profileImg: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  cameraBtn: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
  },
  cameraIcon: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
  },
  formSection: {
    paddingHorizontal: 24,
    marginTop: 8,
  },
  inputLabel: {
    fontSize: 21,
    fontWeight: 'bold',
    color: '#222',
    marginTop: 35,
    marginBottom: 6,
  },
  input: {
    backgroundColor: '#fafafa',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#222',
    marginBottom: 2,
    marginTop: 10,
    marginLeft: -1,
  },
  input2: {
    backgroundColor: '#fafafa',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    paddingHorizontal: 14,
    paddingTop: 12,
    fontSize: 15,
    color: '#222',
    marginBottom: 2,
    marginTop: 10,
    marginLeft: -1,
    textAlign: 'left',
    textAlignVertical: 'top',
    height: 150,
  },
  inputDisabled: {
    color: '#bbb',
    backgroundColor: '#f2f2f2',
  },
  inputMultiline: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  inputHint: {
    fontSize: 12,
    color: '#aaa',
    marginBottom: 2,
    marginLeft: 2,
    marginTop: 2,
  },
  regionSelectBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fafafa',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    paddingHorizontal: 14,
    height: 44,
    marginBottom: 2,
    marginTop: -1,
    marginTop: 10,
  },
  regionText: {
    flex: 1,
    fontSize: 15,
    color: '#222',
  },
  regionPlaceholder: {
    flex: 1,
    fontSize: 15,
    color: '#bbb',
  },
  regionIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    marginLeft: 4,
  },
  bottomSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#fff',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingBottom: 70,
    paddingTop: 12,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 100,
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sheetTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#222',
  },
  sheetClose: {
    fontSize: 22,
    color: '#888',
    padding: 4,
  },
  sheetOptions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 8,
  },
  sheetItem: {
    alignItems: 'center',
    marginHorizontal: 16,
  },
  sheetIcon: {
    width: 44,
    height: 44,
    marginBottom: 6,
    resizeMode: 'contain',
  },
  sheetIcon3: {
    width: 44,
    height: 44,
    marginBottom: 6,
    resizeMode: 'contain',
  },
  sheetLabel: {
    fontSize: 14,
    color: '#333',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    zIndex: 99,
    justifyContent: 'flex-end',
  },
  overlayTouchable: {
    flex: 1,
  },
});

export default styles;
