import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        paddingHorizontal: 16,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    headerIconBtn: {
        padding: 4,
    },
    headerIcon: {
        width: 24,
        height: 24,
        resizeMode: 'contain',
    },
    headerTitle: {
        flex: 1,
        textAlign: 'center',
        fontSize: 18,
        fontWeight: 'bold',
        color: '#222',
        marginHorizontal: 8,
    },
    cropImage: {
        width: '100%',
        height: 160,
        borderRadius: 16,
        marginBottom: 18,
        resizeMode: 'cover',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 6,
        elevation: 5,
    },
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    actionButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#22C55E',
        borderRadius: 12,
        paddingVertical: 12,
        marginHorizontal: 6,
        shadowColor: '#22C55E',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.10,
        shadowRadius: 4,
        elevation: 2,
    },
    actionIcon: {
        width: 22,
        height: 22,
        marginRight: 8,
        resizeMode: 'contain',
        tintColor: '#fff',
    },
    actionText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    memoCardWrapper: {
        flex: 1,
        marginTop: 8,
    },
    memoCard: {
        backgroundColor: '#FEFEE6',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#F3F3C8',
    },
    memoHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    memoTitle: {
        fontWeight: 'bold',
        fontSize: 15,
        color: '#222',
    },
    dotsIcon: {
        width: 20,
        height: 20,
        resizeMode: 'contain',
        tintColor: '#888',
    },
    memoContent: {
        fontSize: 14,
        color: '#222',
        lineHeight: 20,
        marginTop: 2,
    },
    dotsText: {
        fontSize: 22,
        color: '#888',
        fontWeight: 'bold',
        paddingHorizontal: 4,
        paddingVertical: 0,
    },
    photoBox: {
        width: '100%',
        height: 200,
        backgroundColor: '#fff',
        borderRadius: 16,
        marginBottom: 16,
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.25,
        shadowRadius: 8,
        elevation: 8,
        borderWidth: 3,
        borderColor: 'black',
    },
    photo: { width: '120%', height: '120%', borderRadius: 16 },
    icon: { width: 60, height: 60, marginBottom: 8 },
    photoText: { fontSize: 16, color: '#222', fontWeight: 'bold' },
    divider: {
        height: 1,
        backgroundColor: '#E5E5E5',
        marginVertical: 8,
        width: '100%',
    },
});

export default styles;
